### PR TITLE
Fixes vulnerabilities on loofah and nokogiri gems

### PR DESCRIPTION
**Pull request by felipefreitag**

### CODE REVIEW

**Comment by felipefreitag** [comment]
Running `gem dependency _______` on the two vulnerable gems, I got:

screenshot from 2018-03-29 10-35-56

screenshot from 2018-03-29 10-36-31

The list includes `rake`, `hoe`, `concourse`... these are from Rails itself, aren't day? Maybe update Rails from `5.02` to `5.06`? The latest is `5.2`, but I imagine that avoiding too many changes would be a better practice.

**Comment by danielweinmann** [comment]
Shouldn't you be doing the opposite? Those are gems that loofah and nokogiri depend on, right? I believe you should find out which gems depend on them.

**Comment by felipefreitag** [comment]
Whoops. Right. I'm searching for ways of doing that.

**Comment by felipefreitag** [comment]
Got it, but the only gem I see we could update directly would be `awesome_print`.
`rails-html-sanitizer` is used by `actionpack` and `actionview`.

screenshot from 2018-03-29 11-01-48

screenshot from 2018-03-29 11-00-59

**Comment by danielweinmann** [comment]
Ok, so let's put `nokogiri` and `loofah` themselves at our Gemfile in a secure and compatible version.

**Comment by felipefreitag** [comment]
Done, I added the suggested versions.

**Pull request merged**
